/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;

import Modelo.Hash;
import Modelo.usuarios;
import Modelo.usuariosDAO;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.awt.Color;
public class Rusuario extends javax.swing.JFrame {

    public Rusuario() {
        initComponents();
        this.setTitle("Registrar Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        round11 = new componentes.round1();
        nombre = new javax.swing.JTextField();
        Nomlabel = new javax.swing.JLabel();
        ci = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        passconfirm = new javax.swing.JPasswordField();
        id_tipo = new javax.swing.JComboBox<>();
        botones = new componentes.MyButton();
        jLabel6 = new javax.swing.JLabel();
        Cilabel = new javax.swing.JLabel();
        Conlabel = new javax.swing.JLabel();
        Conlabel2 = new javax.swing.JLabel();
        Conlabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        round11.setBackground(new java.awt.Color(217, 216, 217));
        round11.setAlignmentX(0.0F);
        round11.setAlignmentY(0.0F);
        round11.setRoundBottomLeft(30);
        round11.setRoundBottomRight(30);
        round11.setRoundTopLeft(30);
        round11.setRoundTopRight(30);

        nombre.setBackground(new java.awt.Color(195, 195, 195));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        Nomlabel.setBackground(new java.awt.Color(255, 255, 255));
        Nomlabel.setFont(new java.awt.Font("Araboto-Light", 0, 12)); // NOI18N
        Nomlabel.setForeground(new java.awt.Color(75, 75, 78));
        Nomlabel.setText("Nombre y Apellido:");

        ci.setBackground(new java.awt.Color(195, 195, 195));
        ci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciActionPerformed(evt);
            }
        });

        password.setBackground(new java.awt.Color(195, 195, 195));

        passconfirm.setBackground(new java.awt.Color(195, 195, 195));
        passconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passconfirmActionPerformed(evt);
            }
        });

        id_tipo.setBackground(new java.awt.Color(195, 195, 195));
        id_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Administrador", "Profesor", "Asistente" }));
        id_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_tipoActionPerformed(evt);
            }
        });

        botones.setBackground(new java.awt.Color(16, 120, 17));
        botones.setBorder(null);
        botones.setForeground(new java.awt.Color(255, 255, 255));
        botones.setText("Registrar");
        botones.setColor(new java.awt.Color(16, 120, 17));
        botones.setColorClick(new java.awt.Color(16, 168, 2));
        botones.setColorOver(new java.awt.Color(16, 84, 17));
        botones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botones.setRadius(30);
        botones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonesActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Araboto-Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 44, 44));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REGISTRAR USUARIO");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        Cilabel.setBackground(new java.awt.Color(255, 255, 255));
        Cilabel.setFont(new java.awt.Font("Araboto-Light", 0, 12)); // NOI18N
        Cilabel.setForeground(new java.awt.Color(75, 75, 78));
        Cilabel.setText("Cedula de Identidad:");

        Conlabel.setBackground(new java.awt.Color(255, 255, 255));
        Conlabel.setFont(new java.awt.Font("Araboto-Light", 0, 12)); // NOI18N
        Conlabel.setForeground(new java.awt.Color(75, 75, 78));
        Conlabel.setText("Contraseña:");

        Conlabel2.setBackground(new java.awt.Color(255, 255, 255));
        Conlabel2.setFont(new java.awt.Font("Araboto-Light", 0, 12)); // NOI18N
        Conlabel2.setForeground(new java.awt.Color(75, 75, 78));
        Conlabel2.setText("Confirmar Contraseña:");

        Conlabel3.setBackground(new java.awt.Color(255, 255, 255));
        Conlabel3.setFont(new java.awt.Font("Araboto-Light", 0, 12)); // NOI18N
        Conlabel3.setForeground(new java.awt.Color(75, 75, 78));
        Conlabel3.setText("Rol del Usuario:");

        javax.swing.GroupLayout round11Layout = new javax.swing.GroupLayout(round11);
        round11.setLayout(round11Layout);
        round11Layout.setHorizontalGroup(
            round11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(round11Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(round11Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(botones, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(round11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(round11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Nomlabel)
                    .addComponent(Conlabel)
                    .addComponent(Cilabel)
                    .addComponent(Conlabel2)
                    .addComponent(Conlabel3))
                .addGap(18, 18, 18)
                .addGroup(round11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ci, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passconfirm, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(id_tipo, 0, 173, Short.MAX_VALUE)
                    .addComponent(nombre))
                .addGap(17, 17, 17))
        );
        round11Layout.setVerticalGroup(
            round11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(round11Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(round11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nomlabel))
                .addGap(18, 18, 18)
                .addGroup(round11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ci, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cilabel))
                .addGap(18, 18, 18)
                .addGroup(round11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Conlabel))
                .addGap(18, 18, 18)
                .addGroup(round11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Conlabel2))
                .addGap(18, 18, 18)
                .addGroup(round11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Conlabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(botones, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(round11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(round11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_tipoActionPerformed

    }//GEN-LAST:event_id_tipoActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void ciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciActionPerformed

    private void passconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passconfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passconfirmActionPerformed

    private void botonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonesActionPerformed
      
	usuariosDAO modSql = new usuariosDAO();
        usuarios mod = new usuarios();

        String pass = new String(password.getPassword());
        String passcon = new String(passconfirm.getPassword());

        if (ci.getText().equals("") || password.equals("") || passconfirm.equals("") || nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Los campos están vacíos, por favor, llenar todos los campos.");
        } else {
            if (pass.equals(passcon)) {

                if (modSql.existeUsuario(ci.getText()) == 0) {

                    String nuevoPass = Hash.sha1(pass);
                    mod.setCi(ci.getText());
                    mod.setPassword(nuevoPass);
                    mod.setNombre(nombre.getText());

                    int selectedIndex = id_tipo.getSelectedIndex(); // Obtiene el índice seleccionado

                    switch (selectedIndex) {
                        case 1: // Administrador
                        mod.setId_tipo(1);
                        break;
                        case 2: // Profesor
                        mod.setId_tipo(2);
                        break;
                        case 3: // Asistente
                        mod.setId_tipo(3);
                        break;
                        default:
                        JOptionPane.showMessageDialog(null, "Por favor seleccione un tipo de usuario.");
                        return; // Salir del método si no se selecciona un tipo válido
                    }

                    if (modSql.registrar(mod)) {
                        JOptionPane.showMessageDialog(null, "Registro guardado exitosamente");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Error al guardar el usuario");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "El usuario ya existe");
                }
            } else {
                JOptionPane.showMessageDialog(null, "las contraseñas no coinciden");
            }

        }               // TODO add your handling code here:
    }//GEN-LAST:event_botonesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cilabel;
    private javax.swing.JLabel Conlabel;
    private javax.swing.JLabel Conlabel2;
    private javax.swing.JLabel Conlabel3;
    private javax.swing.JLabel Nomlabel;
    private componentes.MyButton botones;
    public javax.swing.JTextField ci;
    private javax.swing.JComboBox<String> id_tipo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombre;
    private javax.swing.JPasswordField passconfirm;
    private javax.swing.JPasswordField password;
    private componentes.round1 round11;
    // End of variables declaration//GEN-END:variables
}
