/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package notification;

import javax.swing.Timer;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Chrys
 */
public class NotificacionExitoso extends javax.swing.JFrame {

    private static final int TIEMPO_CIERRE_MS = 4000;
    private static final int MARGEN_SUPERIOR = 50;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NotificacionExitoso.class.getName());

    /**
     * Creates new form NotificacionFaltaSeleccionarnuv
     */
    public NotificacionExitoso(String mensajeUno, String mensajeDos) {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        initComponents();
        setAlwaysOnTop(true);
        Msj1.setText(mensajeUno);
        Msj2.setText(mensajeDos);
        posicionarYTemporizar();
    }

    private void posicionarYTemporizar() {
        // 1. Posicionamiento: Centrado horizontalmente y arriba
        centrarArriba();

        // 2. Cierre automático: Inicializamos y arrancamos el Timer
        iniciarCierreAutomatico();
    }

    private void centrarArriba() {
        // Obtiene las dimensiones de la pantalla completa
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Obtiene las dimensiones del JFrame actual
        int frameWidth = getWidth();
        int frameHeight = getHeight();

        // Calcula la posición X para centrar horizontalmente:
        int x = (screenSize.width - frameWidth) / 2;

        // La posición Y es el margen superior deseado:
        int y = MARGEN_SUPERIOR;

        // Establece la nueva ubicación del JFrame
        setLocation(x, y);
    }

    private void iniciarCierreAutomatico() {
        // Creamos un ActionListener que se ejecutará cuando el Timer termine
        ActionListener closeAction = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ((Timer) e.getSource()).stop();
                dispose();
            }
        };

        // Creamos el Timer: se dispara una vez (4000 ms)
        Timer timer = new Timer(TIEMPO_CIERRE_MS, closeAction);
        timer.setRepeats(false); // Asegura que solo se ejecute una vez
        timer.start(); // Inicia la cuenta regresiva
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        round11 = new componentes.round1();
        panelRound2 = new Clases.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        Msj2 = new javax.swing.JLabel();
        Msj1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        round11.setBackground(new java.awt.Color(217, 216, 217));
        round11.setRoundBottomLeft(40);
        round11.setRoundBottomRight(40);
        round11.setRoundTopLeft(40);
        round11.setRoundTopRight(40);
        round11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(82, 197, 255));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);
        panelRound2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOTIFICACIÓN");
        panelRound2.add(jLabel1, new java.awt.GridBagConstraints());

        round11.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 330, -1));

        Msj2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Msj2.setForeground(new java.awt.Color(30, 30, 30));
        Msj2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Msj2.setText("Msj2");
        round11.add(Msj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 370, 20));

        Msj1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Msj1.setForeground(new java.awt.Color(30, 30, 30));
        Msj1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Msj1.setText("Msj1");
        round11.add(Msj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 370, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(round11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(round11, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Msj1;
    private javax.swing.JLabel Msj2;
    private javax.swing.JLabel jLabel1;
    private Clases.PanelRound panelRound2;
    private componentes.round1 round11;
    // End of variables declaration//GEN-END:variables
}
