package notification;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;



public class PrevisualizarInfo extends javax.swing.JDialog {
    private String proyectoUrl;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrevisualizarInfo.class.getName());

    public PrevisualizarInfo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new componentes.round1();
        panelRound2 = new Clases.PanelRound();
        txtFDPresentacionPre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new componentes.MyButton();
        btnEditar = new componentes.MyButton();
        btnEnlace = new componentes.MyButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSedePre = new javax.swing.JLabel();
        btnCapture1 = new componentes.MyButton();
        jLabel10 = new javax.swing.JLabel();
        txtTituloPre = new javax.swing.JLabel();
        txtIntegrantesPre = new javax.swing.JLabel();
        txtProfesorPre = new javax.swing.JLabel();
        txtIdPre = new javax.swing.JLabel();
        txtTrayectoPre = new javax.swing.JLabel();
        txtPNFPre = new javax.swing.JLabel();
        txtSeccionPre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelRound1.setBackground(new java.awt.Color(217, 216, 217));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(82, 197, 255));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFDPresentacionPre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFDPresentacionPre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtFDPresentacionPre.setText("Presentarán el dia:");
        panelRound2.add(txtFDPresentacionPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 0, 220, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PreVisualizacion");
        panelRound2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Presentarán el dia:");
        panelRound2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 680, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Identificador:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 120, 30));

        btnSalir.setBackground(new java.awt.Color(254, 61, 61));
        btnSalir.setBorder(null);
        btnSalir.setForeground(new java.awt.Color(255, 248, 248));
        btnSalir.setText("SALIR");
        btnSalir.setBorderColor(new java.awt.Color(217, 216, 217));
        btnSalir.setColor(new java.awt.Color(254, 61, 61));
        btnSalir.setColorClick(new java.awt.Color(254, 50, 18));
        btnSalir.setColorOver(new java.awt.Color(254, 61, 84));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalir.setRadius(20);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelRound1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 120, 50));

        btnEditar.setBackground(new java.awt.Color(62, 115, 248));
        btnEditar.setBorder(null);
        btnEditar.setForeground(new java.awt.Color(255, 248, 248));
        btnEditar.setText("EDITAR");
        btnEditar.setBorderColor(new java.awt.Color(217, 216, 217));
        btnEditar.setColor(new java.awt.Color(62, 115, 248));
        btnEditar.setColorClick(new java.awt.Color(62, 96, 234));
        btnEditar.setColorOver(new java.awt.Color(103, 181, 255));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEditar.setRadius(15);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panelRound1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 120, 50));

        btnEnlace.setBackground(new java.awt.Color(62, 115, 248));
        btnEnlace.setBorder(null);
        btnEnlace.setForeground(new java.awt.Color(255, 248, 248));
        btnEnlace.setText("ENLACE");
        btnEnlace.setBorderColor(new java.awt.Color(217, 216, 217));
        btnEnlace.setColor(new java.awt.Color(62, 115, 248));
        btnEnlace.setColorClick(new java.awt.Color(62, 96, 234));
        btnEnlace.setColorOver(new java.awt.Color(103, 181, 255));
        btnEnlace.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEnlace.setRadius(15);
        btnEnlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnlaceActionPerformed(evt);
            }
        });
        panelRound1.add(btnEnlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 120, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Integrantes:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 120, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("C.I Profesor/a");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 120, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Sede:");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 100, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Trayecto:");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 120, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Sección:");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("PNF:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 120, 30));

        txtSedePre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSedePre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSedePre.setText("-");
        txtSedePre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(txtSedePre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 200, 30));

        btnCapture1.setBackground(new java.awt.Color(62, 115, 248));
        btnCapture1.setBorder(null);
        btnCapture1.setForeground(new java.awt.Color(255, 248, 248));
        btnCapture1.setText("CAPTURAR");
        btnCapture1.setBorderColor(new java.awt.Color(217, 216, 217));
        btnCapture1.setColor(new java.awt.Color(62, 115, 248));
        btnCapture1.setColorClick(new java.awt.Color(62, 96, 234));
        btnCapture1.setColorOver(new java.awt.Color(103, 181, 255));
        btnCapture1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCapture1.setRadius(15);
        btnCapture1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapture1ActionPerformed(evt);
            }
        });
        panelRound1.add(btnCapture1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 120, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Titulo:");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 30));

        txtTituloPre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTituloPre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTituloPre.setText("-");
        txtTituloPre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(txtTituloPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 220, 30));

        txtIntegrantesPre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIntegrantesPre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtIntegrantesPre.setText("-");
        txtIntegrantesPre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(txtIntegrantesPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 220, 30));

        txtProfesorPre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtProfesorPre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProfesorPre.setText("-");
        txtProfesorPre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(txtProfesorPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 220, 30));

        txtIdPre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIdPre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtIdPre.setText("-");
        txtIdPre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(txtIdPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 220, 30));

        txtTrayectoPre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTrayectoPre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTrayectoPre.setText("-");
        txtTrayectoPre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(txtTrayectoPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 210, 30));

        txtPNFPre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPNFPre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtPNFPre.setText("-");
        txtPNFPre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(txtPNFPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 210, 30));

        txtSeccionPre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSeccionPre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSeccionPre.setText("-");
        txtSeccionPre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(txtSeccionPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEnlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnlaceActionPerformed
if (this.proyectoUrl == null || this.proyectoUrl.trim().isEmpty() || this.proyectoUrl.equals("null")) {
        JOptionPane.showMessageDialog(this, "Este proyecto no tiene un enlace asociado.", "Enlace no disponible", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
            Desktop.getDesktop().browse(new URI(this.proyectoUrl));
        } else {
            JOptionPane.showMessageDialog(this, "Tu sistema no soporta abrir enlaces de esta forma.", "Función no soportada", JOptionPane.ERROR_MESSAGE);
        }
    } catch (URISyntaxException | IOException ex) {
        JOptionPane.showMessageDialog(this, "No se pudo abrir el enlace. Verifique que la URL sea válida.\nError: " + ex.getMessage(), "Error al abrir enlace", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEnlaceActionPerformed
public void setProyectoUrl(String url) {
        this.proyectoUrl = url;
    }
    private void btnCapture1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapture1ActionPerformed
        System.out.println("--> Botón presionado. Iniciando proceso de captura como PNG...");

        try {
            // --- 1. Especifica el componente que quieres capturar ---
            // Cambia "this" si quieres capturar otro componente (e.g., un JPanel específico).
            java.awt.Component componentToCapture = this;
            System.out.println("--> Objeto a capturar: " + componentToCapture.getClass().getName());

            // Crea una imagen en memoria del tamaño del componente
            java.awt.image.BufferedImage image = new java.awt.image.BufferedImage(
                    componentToCapture.getWidth(),
                    componentToCapture.getHeight(),
                    java.awt.image.BufferedImage.TYPE_INT_ARGB // Usamos ARGB para soportar transparencia si es necesario
            );

            // Obtiene el contexto gráfico de la imagen y dibuja el componente en él
            java.awt.Graphics2D g = image.createGraphics();
            componentToCapture.paint(g);
            g.dispose(); // Libera los recursos gráficos
            System.out.println("--> La captura del componente se ha dibujado en la memoria.");

            // --- 2. Guarda la imagen en un archivo PNG ---
            // Define la ruta y el nombre del archivo PNG de salida
            String outputPath = "captura_de_pantalla.png";

            // Creamos el archivo
            java.io.File outputFile = new java.io.File(outputPath);

            // Mostramos la ruta completa donde se guardará el archivo
            System.out.println("--> Intentando guardar el PNG en la ruta: " + outputFile.getAbsolutePath());

            // Escribe la imagen capturada en el archivo PNG
            // "ImageIO.write" es parte de la API estándar de Java, no necesita librerías externas.
            javax.imageio.ImageIO.write(image, "PNG", outputFile);

            System.out.println("--> ¡ÉXITO! La imagen PNG se ha creado y guardado.");

            // Muestra un mensaje de éxito
            javax.swing.JOptionPane.showMessageDialog(this, "¡Captura guardada como " + outputPath + "!");

        } catch (Exception ex) { // Capturamos cualquier excepción para mostrarla
            System.err.println("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
            System.err.println("!!! OCURRIÓ UN ERROR QUE DETUVO EL PROCESO !!!");
            System.err.println("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");

            ex.printStackTrace(); // Imprime el rastro completo del error en la consola

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al guardar la captura PNG: " + ex.getMessage()
                    + "\nRevisa la consola de salida (Output) para más detalles.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_btnCapture1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.MyButton btnCapture1;
    private componentes.MyButton btnEditar;
    private componentes.MyButton btnEnlace;
    private componentes.MyButton btnSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private componentes.round1 panelRound1;
    private Clases.PanelRound panelRound2;
    public javax.swing.JLabel txtFDPresentacionPre;
    public javax.swing.JLabel txtIdPre;
    public javax.swing.JLabel txtIntegrantesPre;
    public javax.swing.JLabel txtPNFPre;
    public javax.swing.JLabel txtProfesorPre;
    public javax.swing.JLabel txtSeccionPre;
    public javax.swing.JLabel txtSedePre;
    public javax.swing.JLabel txtTituloPre;
    public javax.swing.JLabel txtTrayectoPre;
    // End of variables declaration//GEN-END:variables
}
